### ISSUE TITLE
i have below error

### ISSUE THREAD

**Issue by cviacmob** [oogbox/odoo-mobile#4]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 3 path $[0]
at com.google.gson.Gson.fromJson(Gson.java:899)
at com.google.gson.Gson.fromJson(Gson.java:852)
at com.google.gson.Gson.fromJson(Gson.java:801)
at com.google.gson.Gson.fromJson(Gson.java:773)
at oogbox.api.odoo.client.helper.data.OdooResult.getRecords(Unknown Source:57)
at com.vvsugar.activity.ReminderService$13.onResult(ReminderService.java:686)
at oogbox.api.odoo.client.a.onResponse(Unknown Source:226)
at oogbox.api.odoo.client.a.onResponse(Unknown Source:2)
at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:90)
at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6753)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 3 path $[0]
at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
at com.google.gson.Gson.fromJson(Gson.java:887)
at com.google.gson.Gson.fromJson(Gson.java:852) 
at com.google.gson.Gson.fromJson(Gson.java:801) 
at com.google.gson.Gson.fromJson(Gson.java:773) 
at oogbox.api.odoo.client.helper.data.OdooResult.getRecords(Unknown Source:57) 
at com.vvsugar.activity.ReminderService$13.onResult(ReminderService.java:686) 
at oogbox.api.odoo.client.a.onResponse(Unknown Source:226) 
at oogbox.api.odoo.client.a.onResponse(Unknown Source:2) 
at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:90) 
at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102) 
at android.os.Handler.handleCallback(Handler.java:790) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loop(Looper.java:164) 
at android.app.ActivityThread.main(ActivityThread.java:6753) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

public void attendance() {
        try {
            ODomain mWeb = new ODomain();
            OdooFields fields = new OdooFields();
            fields.addAll("id", "__last_update", "user_id", "approved_date", "state", "visit_start_date", "name", "visit_end_date");
            int offset = 0;
            int limit = 80;
            String sorting = "";
            client.searchRead("plot.visit", mWeb, fields, offset, limit, sorting, new IOdooResponse() {
                @Override
                public void onResult(OdooResult result) {
                    OdooRecord[] records = result.getRecords();
                    AmtPref.getInstance().writeString(Keys.LAST_SYNC_ATTENDANCE, AppUtils.getCurrentDateSync());
                    for (OdooRecord record : records) {
                        AttendanceMasterDb masterDb = new AttendanceMasterDb(record.getInt("id"), record.getString("__last_update"), record.getString("user_id"), record.getString("approved_date"), record.getString("state"), record.getString("visit_start_date"), record.getString("name"), record.getString("visit_end_date"));
                        masterDb.save();
                    }
                }
            });
        } catch (NegativeArraySizeException e) {
            AmtLog.e("JOB", e.getMessage(), e);
        }
    }

**Comment by bunny-oogbox** [comment]
Hello @cviacmob 
We are on it. It will soon be resolved in the upcoming version.
https://github.com/oogbox/odoo-mobile-api/issues/26
Thanks.
